### ISSUE TITLE
remote container not opening.

### ISSUE THREAD

**Issue by rajeshmandava** [realsh00p/funwithcache#1]
[21 ms] Remote-Containers 0.234.0 in VS Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5).
[21 ms] Start: Resolving Remote
[32 ms] Setting up container for folder or workspace: /Users/rajeshmandava/Dev/cpp/funwithcache
[34 ms] Start: Check Docker is running
[34 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[151 ms] Server API version: 1.41
[152 ms] Start: Run: docker volume ls -q
[268 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/rajeshmandava/Dev/cpp/funwithcache --filter label=vsch.quality=stable
[366 ms] Start: Run: /Applications/Visual Studio Code.app/Contents/MacOS/Electron /Users/rajeshmandava/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/rajeshmandava/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder /Users/rajeshmandava/Dev/cpp/funwithcache --workspace-mount-consistency cached --id-label vsch.local.folder=/Users/rajeshmandava/Dev/cpp/funwithcache --id-label vsch.quality=stable --log-level debug --log-format json --config /Users/rajeshmandava/Dev/cpp/funwithcache/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[456 ms] remote-containers 0.234.0.
[456 ms] Start: Resolving Remote
[457 ms] Start: Run: git rev-parse --show-cdup
[465 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/rajeshmandava/Dev/cpp/funwithcache --filter label=vsch.quality=stable
[567 ms] Start: Run: docker events --format {{json .}} --filter event=start
[568 ms] Start: Starting container
[568 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/Users/rajeshmandava/Dev/cpp/funwithcache,target=/workspaces/funwithcache,consistency=cached --mount source=/tmp/.X11-unix,target=/tmp/.X11-unix,type=bind,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=/Users/rajeshmandava/Dev/cpp/funwithcache -l vsch.quality=stable --init --cap-add=SYS_PTRACE --cap-add=SYS_NICE --cap-add=CAP_NET_ADMIN --cap-add=CAP_IPC_LOCK --security-opt seccomp=unconfined --entrypoint /bin/sh funwithprofiler:0.0.1 -c echo Container started
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /tmp/.X11-unix.
See 'docker run --help'.
[738 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/rajeshmandava/Dev/cpp/funwithcache --filter label=vsch.quality=stable
[837 ms] Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/Users/rajeshmandava/Dev/cpp/funwithcache,target=/workspaces/funwithcache,consistency=cached --mount source=/tmp/.X11-unix,target=/tmp/.X11-unix,type=bind,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=/Users/rajeshmandava/Dev/cpp/funwithcache -l vsch.quality=stable --init --cap-add=SYS_PTRACE --cap-add=SYS_NICE --cap-add=CAP_NET_ADMIN --cap-add=CAP_IPC_LOCK --security-opt seccomp=unconfined --entrypoint /bin/sh funwithprofiler:0.0.1 -c echo Container started
[837 ms] trap "exit 0" 15
[837 ms] exec "$@"
[837 ms] while sleep 1 & wait $!; do :; done -
[837 ms]     at IR (/Users/rajeshmandava/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:221:995)
[837 ms]     at zy (/Users/rajeshmandava/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:221:933)
[837 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[837 ms]     at async $R (/Users/rajeshmandava/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:2007)
[837 ms]     at async Zy (/Users/rajeshmandava/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:3112)
[837 ms]     at async BR (/Users/rajeshmandava/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:12448)
[837 ms]     at async qR (/Users/rajeshmandava/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:12204)
[838 ms] Exit code 1
[840 ms] Command failed: /Applications/Visual Studio Code.app/Contents/MacOS/Electron /Users/rajeshmandava/.vscode/extensions/ms-vscode-remote.remote-containers-0.234.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/rajeshmandava/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder /Users/rajeshmandava/Dev/cpp/funwithcache --workspace-mount-consistency cached --id-label vsch.local.folder=/Users/rajeshmandava/Dev/cpp/funwithcache --id-label vsch.quality=stable --log-level debug --log-format json --config /Users/rajeshmandava/Dev/cpp/funwithcache/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[840 ms] Exit code 1

**Comment by realsh00p** [comment]
I'll admit this project isn't that well documented :)

Did you build the docker image first?
```
$ cd docker
$ ./docker_build.sh
```

**Comment by realsh00p** [comment]
I've recently discovered that one can actually just point out the Dockerfile in 'devcontainer.json' and then vscode would just build the container by itself. Should probably add that.

**Comment by rajeshmandava** [comment]
I guess it's going be differ from Linux to Mac Os, I will point to the dockerfile in my local repo, now that i have already built once.

**Comment by rajeshmandava** [comment]
@realsh00p 
I couldn't push to remote branch nor master, Can you create a remote branch so, i can send in PR for build instructions

**Comment by realsh00p** [comment]
You are now a collaborator and should be able to push remote branches

**Comment by rajeshmandava** [comment]
Great. Thanks
